name = "gift-album-backend"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "7f64008189ec49a7938d402700845082"

[[kv_namespaces]]
binding = "GIFT_KV"
id = "42ad0c4238f641d5afee3e3dca5e8d4c"
